#!/bin/sh
### BEGIN INIT INFO
# Provides: avaproxy
# Required-Start: $network SessionManager
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Spirent Avalanche Proxy server
# Description: Spirent Avalanche Proxy server
### END INIT INFO

WORKING_FOLDER=/root/work/avaproxy
DAEMON=$WORKING_FOLDER/server.py
DAEMON_ARGS="-p 5001"

PIDFILE=/var/run/avaproxy.pid

# check existed process
test -x $CMD || exit 0

start() {
    echo "Start AVA Proxy server ..."
    start-stop-daemon --start --quiet --background --exec $DAEMON --make-pidfile --pidfile $PIDFILE -d $WORKING_FOLDER -- $DAEMON_ARGS
    result=$?
    if [ $result != "0" ]
    then
      pid=`cat $PIDFILE`
      echo "daemon is already running. (pid=${pid})"
      exit 1
    fi
}

stop() {
    echo "Stop AVA Proxy server ..."
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    result=$?
    if [ $result != "0" ]
    then
      echo "daemon is not running. (check $PIDFILE)."
      exit 1
    fi
    rm -f $PIDFILE
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "usage: 0 {start|stop|status|restart}"
esac

exit 0



