# $Rev: 1880 $
# $Date: 2019-03-10 15:28:46 +0900 (日, 10 3 2019) $
# $Author: $

auth:
    plain-text: 
        default:
            user: <user>
            pass: <password>
        samurai:
            user: <user>
            pass: <password>
        alcatel:
            user: <user>
            pass: <password>
        vmware-esxi:
            user: <user>
            pass: <password>

    public-key: # for Public Key authentication
        default:
            user: robot
            key: $HOME/.ssh/robot_id_rsa
        test:
            user: jenkins
            key:  /var/lib/jenkins/.ssh/id_rsa
