# -*- coding: utf-8 -*-
# $Rev: 2117 $
# $Date: 2019-07-29 09:55:17 +0900 (月, 29 7 2019) $
# $Author: $

device:
    Example-device:
        type: Example
        description: Example
        ip: 1.1.1.1
        port: 1111