# -*- coding: utf-8 -*-

*** Setting ***
# RENAT libraries
Library                     SeleniumLibrary                timeout=15s     implicit_wait=15s
Library                     DateTime
Library                     OperatingSystem
Library                     ${RENAT_PATH}/Common.py
Library                     ${RENAT_PATH}/Tool.py
Library                     ${RENAT_PATH}/AChannel.py
Library                     ${RENAT_PATH}/VChannel.py
Library                     ${RENAT_PATH}/Router.py
Library                     ${RENAT_PATH}/WebApp.py
Library                     ${RENAT_PATH}/Logger.py
Library                     ${RENAT_PATH}/Extra.py

