# This is a basic workflow to help you get started with Actions

name: Run RENAT tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
        GITHUB_WORKSPACE: ${{ github.workspace }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

#       - name: Get timestamp
#         id: time_stamp
#         run: |
#             echo ::set-output name=value::$(date "+%Y%m%d_%H%M%S")

#       - name: Checkout RENAT
#         uses: actions/checkout@v2
#         with:
#             repository: bachng2017/RENAT
#             path: renat/renat_project
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.CR_PAT }}
# 
#       - name: Login to Dockerhub
#         uses: docker/login-action@v1
#         with:
#           username: bachng
#           password: ${{ secrets.DOCKER_PASSWORD }}

#      -
#        name: Cache Docker layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-

#       - name: Build and Load
#         uses: docker/build-push-action@v2
#         with:
#             push: false
#             load: true
#             context: renat
#             file: renat/Dockerfile
#             tags: ghcr.io/bachng2017/renat_base7:latest
#             # cache-from: type=local,src=/tmp/.buildx-cache
#             # cache-to: mode=max,type=local,dest=/tmp/.buildx-cache

      - name: Run Tests
        run: |
            cd .test
            docker-compose up --exit-code-from test_renat


